@extends('layouts.app')
@section('title', '社員管理')
@section('content')
<div class="page-header"><div><div class="eyebrow">EMPLOYEES</div><h1>社員一覧</h1><p class="lead">一般社員（1）と社員管理者（9）を同じ社員台帳で管理します。</p></div><a class="button button-primary" href="{{ route('company.employees.create') }}">社員を登録</a></div>
<div class="card"><div class="page-header"><form class="search" method="get"><input name="q" value="{{ request('q') }}" placeholder="社員番号・ログインID・氏名・メール"><button class="button button-secondary">検索</button></form><div class="toolbar"><a class="button button-secondary" href="{{ route('company.employees.csv-template') }}">CSV見本</a><form class="toolbar" method="post" action="{{ route('company.employees.import') }}" enctype="multipart/form-data">@csrf<input type="file" name="csv" accept=".csv" required style="width:230px"><button class="button button-secondary">CSV取込</button></form></div></div>
<div class="table-wrap"><table><thead><tr><th>部署</th><th>社員番号</th><th>ログインID</th><th>社員名</th><th>メール</th><th>ロック</th><th>管理者権限</th><th></th></tr></thead><tbody>
@forelse($employees as $employee)<tr><td>{{ $employee->department?->name ?? '未設定' }}</td><td>{{ $employee->employee_number }}</td><td>{{ $employee->login_id }}</td><td><strong>{{ $employee->name }}</strong></td><td>{{ $employee->email }}</td><td>{{ $employee->lock_status ? 'ロック中' : '—' }}</td><td>{{ $employee->permission?->value }}：{{ $employee->permission?->label() }}</td><td><div class="actions">
@if($emailTemplates->isNotEmpty())<form method="post" action="{{ route('company.employees.send-email', $employee) }}">@csrf<select name="email_template_id" style="max-width:150px">@foreach($emailTemplates as $template)<option value="{{ $template->id }}">{{ $template->name }}</option>@endforeach</select><button class="button button-secondary button-small">メール送信</button></form>@endif
<a class="button button-secondary button-small" href="{{ route('company.employees.edit', $employee) }}">編集</a><form method="post" action="{{ route('company.employees.reset-password', $employee) }}">@csrf<button class="button button-secondary button-small">パスワード再発行</button></form>@if($employee->lock_status)<form method="post" action="{{ route('company.employees.unlock', $employee) }}">@csrf<button class="button button-secondary button-small">ロック解除</button></form>@endif<form method="post" action="{{ route('company.employees.destroy', $employee) }}" onsubmit="return confirm('社員を削除または停止しますか？')">@csrf @method('delete')<button class="button button-danger button-small">削除</button></form></div></td></tr>
@empty<tr><td colspan="8" class="empty">社員がまだ登録されていません。</td></tr>@endforelse
</tbody></table></div><x-pagination :paginator="$employees" /></div>
@endsection
