@extends('layouts.manage')
@section('title', $template->exists ? 'ベース帳票を編集' : 'ベース帳票を作成')
@section('content')
<div class="page-header"><div><div class="eyebrow">BASE PAYSLIP</div><h1>{{ $template->exists ? 'ベース帳票を編集' : 'ベース帳票を作成' }}</h1><p class="lead">帳票レイアウトと各項目の初期スロットを設定します。</p></div></div>
<form method="post" action="{{ $template->exists ? route('manage.templates.update', $template) : route('manage.templates.store') }}">@csrf @if($template->exists) @method('put') @endif
<section class="card"><div class="form-grid"><div class="field"><label>帳票名</label><input name="name" value="{{ old('name', $template->name) }}" required></div><div class="field"><label>レイアウト</label><select name="layout_type">@foreach($layoutTypes as $value => $label)<option value="{{ $value }}" @selected(old('layout_type', $template->layout_type ?? 'standard')===$value)>{{ $label }}</option>@endforeach</select></div><div class="field field-full"><label>説明</label><textarea name="description">{{ old('description', $template->description) }}</textarea></div><div class="field field-full"><input type="hidden" name="is_active" value="0"><label class="checkbox"><input type="checkbox" name="is_active" value="1" @checked(old('is_active', $template->exists ? $template->is_active : true))>企業へ提供する</label></div></div></section>
<section class="card"><div class="page-header"><div><h2>帳票項目</h2><p class="help">スロットは企業側で再割当できます。</p></div><button class="button button-secondary" type="button" id="add-item">項目を追加</button></div><div id="items">
@php($rows = old('items', $template->exists ? $template->items->map(fn($i) => ['code'=>$i->code,'label'=>$i->label,'category'=>$i->category->value,'data_type'=>$i->data_type,'slot_code'=>$i->slot_code,'is_required'=>$i->is_required])->all() : [['code'=>'basic_salary','label'=>'基本給','category'=>'earning','data_type'=>'amount','slot_code'=>'left_01','is_required'=>true],['code'=>'health_insurance','label'=>'健康保険','category'=>'deduction','data_type'=>'amount','slot_code'=>'right_01','is_required'=>false]]))
@foreach($rows as $index => $item)<div class="item-row"><div class="field"><label>項目コード</label><input name="items[{{ $index }}][code]" value="{{ $item['code'] }}" required></div><div class="field"><label>表示名</label><input name="items[{{ $index }}][label]" value="{{ $item['label'] }}" required></div><div class="field"><label>分類</label><select name="items[{{ $index }}][category]">@foreach($categories as $category)<option value="{{ $category->value }}" @selected($item['category']===$category->value)>{{ $category->label() }}</option>@endforeach</select></div><div class="field"><label>種類</label><select name="items[{{ $index }}][data_type]"><option value="amount" @selected($item['data_type']==='amount')>金額</option><option value="number" @selected($item['data_type']==='number')>数値</option><option value="text" @selected($item['data_type']==='text')>文字</option></select></div><div class="field"><label>初期スロット</label><select name="items[{{ $index }}][slot_code]"><option value="">未割当</option>@foreach($slots as $code=>$label)<option value="{{ $code }}" @selected(($item['slot_code'] ?? '')===$code)>{{ $label }}</option>@endforeach</select></div><label class="checkbox"><input type="checkbox" name="items[{{ $index }}][is_required]" value="1" @checked($item['is_required'] ?? false)>必須</label><button class="button button-danger button-small remove-item" type="button">削除</button></div>@endforeach
</div></section><div class="form-actions"><a class="button button-secondary" href="{{ route('manage.templates.index') }}">戻る</a><button class="button button-primary">保存</button></div></form>
<template id="item-template"><div class="item-row"><div class="field"><label>項目コード</label><input data-name="code" required></div><div class="field"><label>表示名</label><input data-name="label" required></div><div class="field"><label>分類</label><select data-name="category">@foreach($categories as $category)<option value="{{ $category->value }}">{{ $category->label() }}</option>@endforeach</select></div><div class="field"><label>種類</label><select data-name="data_type"><option value="amount">金額</option><option value="number">数値</option><option value="text">文字</option></select></div><div class="field"><label>初期スロット</label><select data-name="slot_code"><option value="">未割当</option>@foreach($slots as $code=>$label)<option value="{{ $code }}">{{ $label }}</option>@endforeach</select></div><label class="checkbox"><input type="checkbox" data-name="is_required" value="1">必須</label><button class="button button-danger button-small remove-item" type="button">削除</button></div></template>
<script>const items=document.querySelector('#items');const bind=()=>document.querySelectorAll('.remove-item').forEach(b=>b.onclick=()=>b.closest('.item-row').remove());document.querySelector('#add-item').onclick=()=>{const node=document.querySelector('#item-template').content.cloneNode(true);const i=items.children.length;node.querySelectorAll('[data-name]').forEach(el=>el.name=`items[${i}][${el.dataset.name}]`);items.appendChild(node);bind()};bind();</script>
@endsection
