@extends('layouts.app')
@section('title', $batch->name)
@section('content')
<div class="page-header"><div><div class="eyebrow">{{ $batch->target_month->format('Y-m') }} / {{ strtoupper($batch->status->value) }}</div><h1>{{ $batch->name }}</h1><p class="lead">{{ $batch->setting->name }} ／ {{ $batch->payslips->count() }}名分</p></div><span class="badge {{ $batch->status === \App\Enums\PayrollBatchStatus::Published ? 'badge-success' : ($batch->status === \App\Enums\PayrollBatchStatus::Scheduled ? 'badge-warning' : 'badge-muted') }}">{{ $batch->status->label() }}</span></div>
@if($batch->status === \App\Enums\PayrollBatchStatus::Draft)
<section class="card"><h2>1. CSVを取り込む</h2><p class="help">項目コードに合わせた専用CSVをダウンロードして金額を入力してください。再取込すると同じ社員の明細を更新します。</p><div class="toolbar" style="margin-top:16px"><a class="button button-secondary" href="{{ route('company.payroll.csv-template', $batch) }}">CSVひな型をダウンロード</a><form class="toolbar" method="post" action="{{ route('company.payroll.import', $batch) }}" enctype="multipart/form-data">@csrf<input type="file" name="csv" accept=".csv" required><button class="button button-primary">取り込む</button></form></div></section>
<section class="card"><h2>2. 確認して承認する</h2><p class="help">承認後は明細内容を変更できません。指定日時になると公開され、通知メールが送信されます。</p><form class="toolbar" style="margin-top:16px" method="post" action="{{ route('company.payroll.approve', $batch) }}" onsubmit="return confirm('内容を確定し、公開予約しますか？')">@csrf<input style="max-width:260px" type="datetime-local" name="scheduled_for" value="{{ old('scheduled_for', now()->addHour()->format('Y-m-d\TH:i')) }}" required><button class="button button-primary">承認して公開予約</button></form></section>
@elseif($batch->status === \App\Enums\PayrollBatchStatus::Scheduled)<div class="alert alert-success">{{ $batch->scheduled_for->format('Y年n月j日 H:i') }}に公開し、社員へ通知します。</div>
@else<div class="alert alert-success">{{ $batch->published_at->format('Y年n月j日 H:i') }}に公開しました。通知済み {{ $batch->payslips->whereNotNull('notified_at')->count() }} / {{ $batch->payslips->count() }}件</div>@endif
<section class="card"><h2>社員別明細と閲覧状況</h2><div class="table-wrap"><table><thead><tr><th>社員番号</th><th>氏名</th><th>部署</th><th>総支給</th><th>控除</th><th>差引支給</th><th>閲覧状況</th><th></th></tr></thead><tbody>@forelse($batch->payslips as $payslip)<tr><td>{{ $payslip->employee->employee_number }}</td><td><strong>{{ $payslip->employee->name }}</strong></td><td>{{ $payslip->employee->department?->name ?? '—' }}</td><td class="numeric">¥{{ number_format($payslip->gross_amount) }}</td><td class="numeric">¥{{ number_format($payslip->deduction_amount) }}</td><td class="numeric"><strong>¥{{ number_format($payslip->net_amount) }}</strong></td><td>@if($payslip->first_viewed_at)<span class="badge badge-success">閲覧済み</span><div class="help">{{ $payslip->first_viewed_at->format('Y/m/d H:i') }}・{{ $payslip->view_count }}回</div>@else<span class="badge badge-muted">未閲覧</span>@endif</td><td><a class="button button-secondary button-small" href="{{ route('company.payroll.payslips.show', [$batch, $payslip]) }}">明細を見る</a></td></tr>@empty<tr><td colspan="8" class="empty">CSVを取り込むと、ここに社員別の明細が表示されます。</td></tr>@endforelse</tbody></table></div></section>
@endsection
