<!doctype html><html lang="ja"><head><meta charset="utf-8"><style>
body{font-family:ipag,sans-serif;color:#172033;font-size:11px}h1{font-size:22px;margin:0}h2{font-size:15px;margin:0}.head{border-bottom:2px solid #172033;padding-bottom:14px;margin-bottom:20px}.company{float:left;width:55%}.employee{text-align:right}.clear{clear:both}.meta{color:#687586;font-size:9px;margin-top:5px}h3{font-size:12px;background:#eef3f5;border-left:4px solid #197568;padding:7px;margin:18px 0 0}table{width:100%;border-collapse:collapse}td{padding:8px;border-bottom:1px solid #dbe3e8}.number{text-align:right}.summary{margin-top:24px;border:1px solid #aebbc5}.summary td{width:33%;border-right:1px solid #aebbc5;text-align:center}.summary strong{display:block;font-size:16px;margin-top:5px}.footer{margin-top:22px;color:#687586;font-size:9px}
</style></head><body>
<div class="head"><div class="company"><div class="meta">{{ $payslip->batch->company->code }}</div><h2>{{ $payslip->batch->company->name }}</h2></div><div class="employee"><h1>{{ $payslip->batch->target_month->format('Y年n月') }} 給与明細</h1><div class="meta">{{ $payslip->employee->name }} 様 ／ 社員番号 {{ $payslip->employee->employee_number }}</div></div><div class="clear"></div></div>
@php($items = collect($payslip->details))
@php($hasSlots = $items->contains(fn($item) => filled($item['slot_code'] ?? null)))
@if($hasSlots)<table><tr>@foreach(['left','right'] as $prefix)<td style="width:50%;vertical-align:top;padding:0 8px"><table>@foreach($items->filter(fn($item) => str_starts_with($item['slot_code'] ?? '', $prefix.'_'))->sortBy('slot_code') as $item)<tr><td>{{ $item['label'] }}</td><td class="number">@if($item['data_type']==='amount')¥{{ number_format((float)$item['value']) }}@else{{ $item['value'] }}@endif</td></tr>@endforeach</table></td>@endforeach</tr></table>@else
@php($groups = $items->groupBy('category'))
@foreach(['earning'=>'支給','deduction'=>'控除','information'=>'勤怠・その他'] as $key => $label)@if($groups->has($key))<h3>{{ $label }}</h3><table>@foreach($groups[$key] as $item)<tr><td>{{ $item['label'] }}</td><td class="number">@if($item['data_type']==='amount')¥{{ number_format((float)$item['value']) }}@else{{ $item['value'] }}@endif</td></tr>@endforeach</table>@endif @endforeach @endif
<table class="summary"><tr><td>総支給額<strong>¥{{ number_format($payslip->gross_amount) }}</strong></td><td>控除合計<strong>¥{{ number_format($payslip->deduction_amount) }}</strong></td><td>差引支給額<strong>¥{{ number_format($payslip->net_amount) }}</strong></td></tr></table><div class="footer">公開日時：{{ $payslip->batch->published_at->format('Y年n月j日 H:i') }}</div>
</body></html>
