@extends('layouts.app')
@section('title', '明細項目を編集')
@section('content')
<div class="page-header"><div><div class="eyebrow">COMPANY PAYSLIP SCHEMA</div><h1>明細項目を編集</h1><p class="lead">{{ $setting->template->name }}をもとにした自社設定です。項目コードがCSV列名になります。</p></div></div>
<form method="post" action="{{ route('company.settings.update', $setting) }}">@csrf @method('put')
<section class="card"><div class="form-grid"><div class="field"><label>設定名</label><input name="name" value="{{ old('name', $setting->name) }}" required></div><div class="field"><input type="hidden" name="is_active" value="0"><label class="checkbox" style="margin-top:32px"><input type="checkbox" name="is_active" value="1" @checked(old('is_active', $setting->is_active))>この設定を使用する</label></div></div></section>
<section class="card"><div class="page-header"><div><h2>自社用の項目</h2><p class="help">不要な項目は「使用する」を外すか、削除できます。</p></div><button class="button button-secondary" type="button" id="add-item">自社項目を追加</button></div><div id="items">
@php($rows = old('items', $setting->items->map(fn($i) => ['code'=>$i->code,'label'=>$i->label,'category'=>$i->category->value,'data_type'=>$i->data_type,'is_required'=>$i->is_required,'is_active'=>$i->is_active])->all()))
@foreach($rows as $index => $item)<div class="item-row"><div class="field"><label>項目コード</label><input name="items[{{ $index }}][code]" value="{{ $item['code'] }}" required></div><div class="field"><label>表示名</label><input name="items[{{ $index }}][label]" value="{{ $item['label'] }}" required></div><div class="field"><label>分類</label><select name="items[{{ $index }}][category]">@foreach($categories as $category)<option value="{{ $category->value }}" @selected($item['category']===$category->value)>{{ $category->label() }}</option>@endforeach</select></div><div class="field"><label>種類</label><select name="items[{{ $index }}][data_type]"><option value="amount" @selected($item['data_type']==='amount')>金額</option><option value="number" @selected($item['data_type']==='number')>数値</option><option value="text" @selected($item['data_type']==='text')>文字</option></select></div><div><input type="hidden" name="items[{{ $index }}][is_active]" value="0"><label class="checkbox"><input type="checkbox" name="items[{{ $index }}][is_active]" value="1" @checked($item['is_active'] ?? true)>使用</label><label class="checkbox"><input type="checkbox" name="items[{{ $index }}][is_required]" value="1" @checked($item['is_required'] ?? false)>必須</label></div><button class="button button-danger button-small remove-item" type="button">削除</button></div>@endforeach
</div></section><div class="form-actions"><a class="button button-secondary" href="{{ route('company.settings.index') }}">戻る</a><button class="button button-primary">保存</button></div></form>
<template id="item-template"><div class="item-row"><div class="field"><label>項目コード</label><input data-name="code" required></div><div class="field"><label>表示名</label><input data-name="label" required></div><div class="field"><label>分類</label><select data-name="category">@foreach($categories as $category)<option value="{{ $category->value }}">{{ $category->label() }}</option>@endforeach</select></div><div class="field"><label>種類</label><select data-name="data_type"><option value="amount">金額</option><option value="number">数値</option><option value="text">文字</option></select></div><div><label class="checkbox"><input type="checkbox" data-name="is_active" value="1" checked>使用</label><label class="checkbox"><input type="checkbox" data-name="is_required" value="1">必須</label></div><button class="button button-danger button-small remove-item" type="button">削除</button></div></template>
<script>const items=document.querySelector('#items');const bind=()=>document.querySelectorAll('.remove-item').forEach(b=>b.onclick=()=>b.closest('.item-row').remove());document.querySelector('#add-item').onclick=()=>{const node=document.querySelector('#item-template').content.cloneNode(true);const i=items.children.length;node.querySelectorAll('[data-name]').forEach(el=>el.name=`items[${i}][${el.dataset.name}]`);items.appendChild(node);bind()};bind();</script>
@endsection
